# Copyright (C) 2025 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@rules_pkg//pkg:install.bzl", "pkg_install")
load("@rules_pkg//pkg:mappings.bzl", "pkg_files", "strip_prefix")
load(
    "//build/kernel/kleaf:kernel.bzl",
    "boot_image",
    "dtb_image",
    "dtbo_image",
    "initramfs",
    "kernel_build",
    "kernel_modules_install",
)
load("//common:modules.bzl", "get_gki_modules_list", "get_kunit_modules_list")

_RAVIOLE_UPSTREAM_MODULES = [
    # SOC_SAMSUNG configs
    "drivers/soc/samsung/exynos_chipid.ko",
    "drivers/soc/samsung/exynos-usi.ko",
    "drivers/i2c/busses/i2c-exynos5.ko",
    # Pixel 6 modules
    "drivers/perf/arm_dsu_pmu.ko",
    "drivers/watchdog/s3c2410_wdt.ko",
    "drivers/misc/eeprom/at24.ko",
    # UFS
    "drivers/phy/samsung/phy-exynos-ufs.ko",
    "drivers/ufs/host/ufs-exynos.ko",
    # max77759
    "drivers/mfd/max77759.ko",
    "drivers/gpio/gpio-max77759.ko",
    "drivers/nvmem/nvmem-max77759.ko",
    # acpm
    "drivers/mailbox/exynos-mailbox.ko",
    "drivers/firmware/samsung/acpm-protocol.ko",
    # s2mpg1x (needs acpm)
    "drivers/mfd/sec-core.ko",
    "drivers/mfd/sec-acpm.ko",
    "drivers/clk/clk-s2mps11.ko",
    "drivers/rtc/rtc-s5m.ko",
    # USB
    "drivers/phy/samsung/phy-exynos5-usbdrd.ko",
    "drivers/usb/dwc3/dwc3-exynos.ko",
    # TCPCi
    "drivers/usb/typec/tcpm/tcpci_maxim.ko",
    # FB/display
    "drivers/video/fbdev/simplefb.ko",
]

kernel_build(
    name = "raviole_upstream",
    srcs = ["//common:kernel_aarch64_sources"],
    outs = [
        "Image.lz4",
        "System.map",
        "modules.builtin",
        "modules.builtin.modinfo",
        "vmlinux",
        "vmlinux.symvers",
    ],
    arch = "arm64",
    ddk_module_headers = ["//common:all_headers_aarch64"],
    defconfig = "//common:arch/arm64/configs/gki_defconfig",
    make_goals = [
        "Image.lz4",
        "modules",
    ],
    makefile = "//common:Makefile",
    module_outs = get_gki_modules_list("arm64") +
                  get_kunit_modules_list("arm64") +
                  _RAVIOLE_UPSTREAM_MODULES,
    pre_defconfig_fragments = [":raviole_gki.fragment"],
    strip_modules = True,
    visibility = ["//visibility:public"],
)

# TODO(b/452633937): Move to GKI and drop this boot_image rule once we can
# enable ARCH_EXYNOS in the gki_defconfig.
boot_image(
    name = "raviole_upstream_boot",
    outs = [
        "boot.img",
    ],
    avb_boot_algorithm = "SHA256_RSA4096",
    avb_boot_key = "@avb_test//:data/testkey_rsa4096.pem",
    avb_boot_partition_name = "boot",
    avb_boot_partition_size = 0x04000000,
    avb_sign_boot_img = True,
    header_version = 4,
    kernel_binary = ":raviole_upstream/Image.lz4",
    kernel_build = ":raviole_upstream",
)

kernel_modules_install(
    name = "raviole_upstream_modules_install",
    kernel_build = ":raviole_upstream",
)

write_file(
    name = "raviole_upstream_vendor_boot_modules_list",
    out = "raviole_upstream_vendor_boot_modules",
    content = _RAVIOLE_UPSTREAM_MODULES,
)

dtb_image(
    name = "raviole_upstream_dtb",
    srcs = ["//devices/google/raviole/dts:gs101-oriole.dtb"],
    out = "dtb.img",
)

dtbo_image(
    name = "raviole_upstream_dtbo",
    srcs = ["//devices/google/raviole/dts:dtbos"],
    opts = [
        "--page_size=4096",
        "--id=/:board_id",
        "--rev=/:board_rev",
    ],
)

initramfs(
    name = "raviole_upstream_initramfs",
    kernel_modules_install = ":raviole_upstream_modules_install",
    modules_list = ":raviole_upstream_vendor_boot_modules_list",
    ramdisk_compression = "lz4",
    trim_unused_modules = True,
)

pkg_files(
    name = "raviole_upstream_dist_files",
    srcs = [
        ":raviole_upstream",
        ":raviole_upstream_boot",
        ":raviole_upstream_dtb",
        ":raviole_upstream_dtbo",
        ":raviole_upstream_initramfs",
        ":raviole_upstream_modules_install",
    ],
    strip_prefix = strip_prefix.files_only(),
    visibility = ["//visibility:private"],
)

pkg_install(
    name = "raviole_upstream_dist",
    srcs = [":raviole_upstream_dist_files"],
    destdir = "out/raviole_upstream/dist",
)
